name: socket_io_common_client
description: Dartlang port of socket.io-client, Support VM(Flutter, cmd, server) and web front-end
version: 0.10.0
author: bixiaopeng <bixiaopeng2007@gmail.com>
homepage: https://github.com/moshoujingli/socket.io-client-dart

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  #logging: ^0.11.3+2
  #socket_io_common: ^0.9.0+1

  logging: ^1.0.0
  socket_io_common:
    git:
      url: https://github.com/kadersaka/socket_io_common-0.9.0

dev_dependencies:
#  test: ">=1.3.0 <2.0.0"
#  build_runner:
#  build_web_compilers:
#  socket_io: any


